promtail_config_scrape_configs:
  - job_name: application
    static_configs:
    - targets:
        - localhost
      labels:
        job: application_logs
        __path__: /app/.logs/*log

promtail_loki_server_url: http://192.168.56.203:3100