- name: "Run Django Local Library Application"
  hosts: "app"
  become: true
  tasks:
    - name: "Run Django Application"
      community.docker.docker_container:
        name: django-app
        image: timurbabs/django:latest
        state: started
        ports:
          - "8000:8000"
...
