---
- name: "Install OpenVPN to Servers Hosts"
  hosts: "server"

  roles:
    - openvpn

- name: "Install OpenVPN to Clients Hosts"
  hosts: "client"

  tasks:
    - name: "Install OpenVPN"
      become: true
      apt:
        name:
          - openvpn
        state: "present"
        update_cache: "yes"

    - name: "Copy client config"
      copy:
        src: "{{ playbook_dir }}/ovpn-client-conf/server1-client1.ovpn"
        dest: "/home/vagrant/server1-{{ openvpn_client_common_name }}.ovpn"
...
